project_id = "jpulnascpktoteamjspw"

[functions.generate-reminder]
verify_jwt = false

[functions.get-vapi-key]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.quickbooks-auth]
verify_jwt = false

[functions.quickbooks-callback]
verify_jwt = false

[functions.quickbooks-sync]
verify_jwt = false

[functions.sage-auth]
verify_jwt = false

[functions.sage-callback]
verify_jwt = false

[functions.sage-sync]
verify_jwt = false
